#pragma once
// =====================
// JSON core definitions
// =====================
#include "JSON_Variant.hpp"
#include "JSON_JNode.hpp"
#include "JSON_Hole.hpp"
#include "JSON_Number.hpp"
#include "JSON_String.hpp"
#include "JSON_Boolean.hpp"
#include "JSON_Null.hpp"
#include "JSON_Object.hpp"
#include "JSON_Array.hpp"
#include "JSON_JNode_Reference.hpp"
#include "JSON_JNode_Creation.hpp"
#include "JSON_JNode_Index.hpp"
#include "JSON_Interfaces.hpp"
#include "JSON_Sources.hpp"
#include "JSON_Destinations.hpp"
